galanin-sign-in-logic : Logic added 4 SignIn page
BrSTU-2022-practice-ToDoCalendar/ToDoCalendar_frontend pull request #16
Opened 2022-06-23 14:54 UTC by Pavel-Innokentevich-Galanin

Целью этого пул реквеста было создать локигу для страницы `SignIn`

- [x] создал в `.env` и в `.env.production` файлах переменную с ссылкой `API`
- [x] поменял `SingIn` на `SignIn`, `SingUp` на `SignUp`
- [x] добавил логику входа (в `SignIn` функция `login`) : при успехе редирект на `Home`, иначе вывод ошики
- [x] добавил при рендринге компонента `Home` проверку существования `refresh` токена, а если его нет, то редирект на `SignIn`
- [x] добавил при рендринге компонента `Home` проверку авторизации `refresh` токена (функция `verify`), а если он не авторизирован, то редирект на `SignIn`

2022-06-23 15:36 UTC, zhvirblis-yuri requested changes

2022-06-23 15:36 UTC, zhvirblis-yuri commented on .env
> +REACT_APP_api_server=http://localhost:8000
.env надо в .gitignore прописать, т.к. этот файл у разных пользователей мб разный, а этот файл переименовать в .env.example например, чтобы пользователи могли знать какой надо .env создать

2022-06-23 15:36 UTC, zhvirblis-yuri commented on .env.production
> +REACT_APP_api_server=http://localhost:8000
Так же как выше

2022-06-23 15:36 UTC, zhvirblis-yuri commented on src/pages/Home/Home.jsx
> +    console.log(refresh_token);
Убрать console.log()

2022-06-23 15:36 UTC, zhvirblis-yuri commented on src/scripts/login.js
> +    console.log({
Убрать console.log()

2022-06-23 15:36 UTC, zhvirblis-yuri commented on src/scripts/verify.js
> +  console.log({
Убрать console.log()

2022-06-23 15:36 UTC, zhvirblis-yuri commented on src/pages/Home/Home.jsx
> +    if (verify(refresh_token) === false) {
Писать `=== false` и `=== null` не надо, можно просто `!` заюзать. И эти два условния можно завернуть в одно `if (!refresh_token || !verify(refresh_token))`

2022-06-23 15:36 UTC, zhvirblis-yuri commented on src/pages/Home/Home.jsx
> +  const [htmlRedirect, setHtmlRedirect] = useState(<></>);
`<></>` для "пустоты" лучше null юзать, целый компонент тянуть не стоит

2022-06-23 15:36 UTC, zhvirblis-yuri commented on src/pages/Home/Home.jsx
> +  function constructor() {
Название constructor запутывает, т.к. можно подумать, что эта функция работает как constructor в классе

2022-06-23 15:36 UTC, zhvirblis-yuri commented on src/pages/Home/Home.jsx
> +          {htmlRedirect}
Костыль, для редиректа можно заюзать https://reactrouterdotcom.fly.dev/docs/en/v6/hooks/use-navigate

2022-06-23 16:30 UTC, pavelhalanin commented on .env
> +REACT_APP_api_server=http://localhost:8000
- [x] удалил файл `.env`
- [x] добавил `.env` в `.gitignore`
- [x] создал файл `.env.example`
- [x] в `README.md` и `README-ru.md` файлах указал команду `cp .env.example .env`

2022-06-23 16:32 UTC, Pavel-Innokentevich-Galanin commented on .env.production
> +REACT_APP_api_server=http://localhost:8000
- [x] удалил файл `.env.production`
- [x] добавил `.env.production` в `.gitignore`
- [x] создал файл `.env.production.example`
- [x] в `README.md` и `README-ru.md` файлах указал команду `cp .env.production.example .env.production`

2022-06-23 18:03 UTC, Pavel-Innokentevich-Galanin commented on src/pages/Home/Home.jsx
> +          {htmlRedirect}
```jsx
  let navigate = useNavigate();

  // Функция, которая вызывается один раз (костыль коструктора)
  useEffect(() => {
    setCalendarDays(calendar_json_example);
    setTasksList(task_today_example);
  }, []);

  // Функция, которая вызывается один раз (костыль коструктора)
  useEffect(() => {
    const refresh_token = localStorage.getItem('refresh');

    // Если нет в локальной базе данных refresh токена, то выйти
    // Если refresh токен не авторизован, то выйти
    if (!refresh_token || !verify(refresh_token)) {
      navigate('/sign-in', { replace: true });
      return;
    }
  }, [navigate]);
```

2022-06-23 18:04 UTC, Pavel-Innokentevich-Galanin commented on src/pages/Home/Home.jsx
> +  function constructor() {
```jsx
  let navigate = useNavigate();

  // Функция, которая вызывается один раз (костыль коструктора)
  useEffect(() => {
    setCalendarDays(calendar_json_example);
    setTasksList(task_today_example);
  }, []);

  // Функция, которая вызывается один раз (костыль коструктора)
  useEffect(() => {
    const refresh_token = localStorage.getItem('refresh');

    // Если нет в локальной базе данных refresh токена, то выйти
    // Если refresh токен не авторизован, то выйти
    if (!refresh_token || !verify(refresh_token)) {
      navigate('/sign-in', { replace: true });
      return;
    }
  }, [navigate]);
```

2022-06-23 18:11 UTC, Pavel-Innokentevich-Galanin commented on src/pages/Home/Home.jsx
> +  const [htmlRedirect, setHtmlRedirect] = useState(<></>);
Смотрел.

Если буду где-то использовать JSX тэг, то буду писать не `= useState(<></>);`, а `= useState(null);`

В коде не использовал.

2022-06-23 18:12 UTC, Pavel-Innokentevich-Galanin commented on src/pages/Home/Home.jsx
> +    if (verify(refresh_token) === false) {
```js
    // Если нет в локальной базе данных refresh токена, то выйти
    // Если refresh токен не авторизован, то выйти
    if (!refresh_token || !verify(refresh_token)) {
      navigate('/sign-in', { replace: true });
      return;
    }
```

2022-06-23 18:12 UTC, Pavel-Innokentevich-Galanin commented on src/scripts/verify.js
> +  console.log({
Убрал.

2022-06-23 18:13 UTC, Pavel-Innokentevich-Galanin commented on src/scripts/login.js
> +    console.log({
Убрал `console.log`.

2022-06-23 18:14 UTC, Pavel-Innokentevich-Galanin commented on src/pages/Home/Home.jsx
> +    console.log(refresh_token);
Убрал `console.log`.

2022-06-23 18:14 UTC, Pavel-Innokentevich-Galanin commented on src/scripts/verify.js
> +  console.log({
Убрал `console.log`.

2022-06-23 18:15 UTC, Pavel-Innokentevich-Galanin commented on src/pages/Home/Home.jsx
> +    console.log(refresh_token);
- [x] убрал `console.log`

2022-06-23 18:15 UTC, Pavel-Innokentevich-Galanin commented on src/scripts/login.js
> +    console.log({
- [x] убрал `console.log`

2022-06-23 18:16 UTC, Pavel-Innokentevich-Galanin commented on src/scripts/verify.js
> +  console.log({
- [x] убрал `console.log`

2022-06-23 18:19 UTC, Pavel-Innokentevich-Galanin commented on src/pages/Home/Home.jsx
> +    if (verify(refresh_token) === false) {
- [x] заменил `x === false` на `!x`
- [x] заменил `x === null` на `!x`
- [x] объединил `if(x){caseA()} if(y){caseA()}` в `if(x || y){caseA()}` 

```jsx
    // Если нет в локальной базе данных refresh токена, то выйти
    // Если refresh токен не авторизован, то выйти
    if (!refresh_token || !verify(refresh_token)) {
      navigate('/sign-in', { replace: true });
      return;
    }
```

2022-06-23 18:20 UTC, Pavel-Innokentevich-Galanin commented on src/pages/Home/Home.jsx
> +  function constructor() {
- [x] убрал функцию `constructor()`: запихнул в два `useEffect`

```jsx
  let navigate = useNavigate();

  // Функция, которая вызывается один раз (костыль коструктора)
  useEffect(() => {
    setCalendarDays(calendar_json_example);
    setTasksList(task_today_example);
  }, []);

  // Функция, которая вызывается один раз (костыль коструктора)
  useEffect(() => {
    const refresh_token = localStorage.getItem('refresh');

    // Если нет в локальной базе данных refresh токена, то выйти
    // Если refresh токен не авторизован, то выйти
    if (!refresh_token || !verify(refresh_token)) {
      navigate('/sign-in', { replace: true });
      return;
    }
  }, [navigate]);
```

2022-06-23 18:21 UTC, Pavel-Innokentevich-Galanin commented on src/pages/Home/Home.jsx
> +          {htmlRedirect}
- [x] вместо тэга `<Navigate />` использовал хук `useNavigate`

```jsx
  let navigate = useNavigate();

  // Функция, которая вызывается один раз (костыль коструктора)
  useEffect(() => {
    setCalendarDays(calendar_json_example);
    setTasksList(task_today_example);
  }, []);

  // Функция, которая вызывается один раз (костыль коструктора)
  useEffect(() => {
    const refresh_token = localStorage.getItem('refresh');

    // Если нет в локальной базе данных refresh токена, то выйти
    // Если refresh токен не авторизован, то выйти
    if (!refresh_token || !verify(refresh_token)) {
      navigate('/sign-in', { replace: true });
      return;
    }
  }, [navigate]);
```

2022-06-23 18:58 UTC, Pavel-Innokentevich-Galanin commented
- [x] поменял у компонента `<Container />` аргумент `innerHTML` на `children`


**СПИСОК ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ**:
1. Composition vs Inheritance – React
    [Electronic resource].
    Mode of access: https://reactjs.org/docs/composition-vs-inheritance.html#containment.
    Date of access: 23.06.2022.

2022-06-23 21:33 UTC, Vhublad approved these changes

2022-06-27 12:26 UTC, zhvirblis-yuri approved these changes

2022-06-27 12:26 UTC, zhvirblis-yuri commented on src/components/Container/README.md
> +<Container children={<div>...</div>} />
Перепиши на `<Container><div>...</div></Container>` - это эквивалентною. props.children - это контент внутри тега

2022-06-27 12:26 UTC, zhvirblis-yuri commented on src/pages/Error404/Error404.jsx
> +  return <Container children={<Header title="Error 404 - Page not found" />} />;
Смотри коммент выше

2022-06-27 12:26 UTC, zhvirblis-yuri commented on src/pages/Home/Home.jsx
>      setCalendarDays(calendar_json_example);
Перемести начальные значения в useState()

2022-06-27 12:26 UTC, zhvirblis-yuri commented on src/pages/Home/Home.jsx
>    const [calendarDays, setCalendarDays] = useState([]);
Смотри коммент ниже

2022-06-27 12:26 UTC, zhvirblis-yuri commented on src/pages/Home/Home.jsx
> +            children={<Header title="Tassker" IconsArray={[<MenuIcon />]} />}
Смотри коммент выше

2022-06-27 12:26 UTC, zhvirblis-yuri commented on src/pages/Home/Home.jsx
> +            children={
Смотри коммент выше

2022-06-27 12:26 UTC, zhvirblis-yuri commented on src/pages/Home/Home.jsx
> +      Footer={<Container children={<Button />} />}
Смотри коммент выше

2022-06-27 12:26 UTC, zhvirblis-yuri commented on src/pages/SignIn/SignIn.jsx
> +    navigate('/', { replace: true });
можно verify_flag сделать true(=== удалить конечно) и navigate туда переместить

2022-06-27 12:27 UTC, merged