add docker to front by back
BrSTU-2022-practice-ToDoCalendar/ToDoCalendar_frontend pull request #38
Opened 2022-06-30 12:17 UTC by mifthebest

Добавил докерфайлы ля запуска только фронта. Я фронт до этого не запускал, иак что если будут ошибки - поправь)
А если все будет норм - буду готовить общий docker-compose.yaml для выгрузки на сервер

2022-06-30 15:03 UTC, Pavel-Innokentevich-Galanin requested changes

2022-06-30 15:03 UTC, pavelhalanin commented on Dockerfile
> +FROM node:12-alpine
Поменяй на версию: `node:16`.

2022-06-30 15:03 UTC, pavelhalanin commented on Dockerfile
> +COPY .env.example /app/.env
Делай копию `.env` у себя на компьютере.

В `.env` файле пропиши вместо `http://localhost:8000` домен сервера.

В Dockerfile пиши `COPY .env /app/.env`.

2022-06-30 15:03 UTC, pavelhalanin commented on Dockerfile
> +COPY .env.production.example /app/.env.production
`.env.production.example` я делал для выгрузки на gh-pages.

Он нам не нужен на сервере.

Убери строчку из Dockerfile `COPY .env.production.example /app/.env.production`.

2022-06-30 15:03 UTC, pavelhalanin commented on docker-compose.yml
> +      - 3000:3000
На фронте порт не `3000`, а `5000`.

Чтобы его не менять, бери порт из `.env` файла.

```yml
ports:
  - ${PORT}:${PORT}
```

2022-06-30 15:03 UTC, pavelhalanin commented on run.sh
> +npm i &&
`npm i` - устанавливает из `package.json`.

`npm ci` - устанавливает из `package-lock.json`.

Помей на `npm ci`.

2022-06-30 15:03 UTC, Pavel-Innokentevich-Galanin commented on run.sh
> +npm run start
Тут надо придумать что сделать:
- либо смотреть папку `build` через `nginx`
- либо смотреть папку `build` через `serve`
- оставить пока `npm run start`, который поднимает сервер для разработки

> Тут `npm run start` запускает dev сервер для разработки.
> 
> Вообще лучше приложение билдить `npm run build` и папку `build` смотреть через `nginx`.
> 
> Либо попробовать установить `npm run serve` и `serve build -l 1234`.

2022-06-30 19:33 UTC, mifthebest commented on Dockerfile
> +COPY ./package.json ./package-lock.json /app/
Не знаю, как у вас, но на бэке отдельное копирование сперва файлов для либ а потом всего остального значительно уменшало время пересборки докера после внесения изменений в код проекта

2022-06-30 19:34 UTC, mifthebest commented on run.sh
>  npm run start
Кодманду вынес в отдельный файл, т.к. ментор питона говорил, что логика выноситься в отдельный скрипт. На установку зависимстей это не распростроняется

2022-07-01 11:35 UTC, Pavel-Innokentevich-Galanin approved these changes

2022-07-01 11:35 UTC, merged